
from setuptools import setup
setup(**{'author': 'puntonim',
 'author_email': 'foo@gmail.com',
 'classifiers': ['Development Status :: 5 - Production/Stable',
                 'Environment :: Web Environment',
                 'Intended Audience :: Developers',
                 'Operating System :: OS Independent',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.6',
                 'Topic :: Internet :: WWW/HTTP'],
 'description': 'Rabbit service client',
 'include_package_data': True,
 'install_requires': ['pkgsettings<1,>=0.12.0', 'requests<3,>=2.19.1'],
 'long_description': "",
 'name': 'service-rabbit',
 'packages': ['service_rabbit'],
 'tests_require': ['tox'],
 'url': 'https://github.com/puntonim/service-rabbit',
 'version': '0.0.1',
 'zip_safe': False})
